---
- name: Configure Nginx
  hosts: web
  become: true

  tasks:
  - name: Install Nginx
    ansible.builtin.apt:
      name: nginx
      state: present

  - name: Configure nginx
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      backup: yes
      mode: '0644'
  
  - name: Add Node.js 18.x repo
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: Add Node.js APT repository
    apt_repository:
      repo: deb https://deb.nodesource.com/node_18.x focal main
      state: present
      filename: nodesource

  - name: Install Node.js
    apt:
      name: nodejs
      state: present
      update_cache: yes

  - name: Ensure app directory exists
    ansible.builtin.file:
      path: /var/www/myapp
      state: directory
      mode: '0755'

  - name: Copy app files to remote server
    ansible.builtin.synchronize:
    src: ./  # your local app folder
    dest: /var/www/myapp/
    rsync_opts:
      - "--exclude=node_modules"
      - "--exclude=.git"
      - "--exclude=terraform"
      - "--exclude=Ansible"

  - name: Install Node.js dependencies
    ansible.builtin.command:
      cmd: npm install
      chdir: /var/www/myapp

  - name: Start Node.js App
    ansible.builtin.command:
      cmd: npm start
      chdir: /var/www/myapp


  - name: Restart Nginx
    ansible.builtin.systemd:
      name: nginx
      state: restarted
      enabled: true


